name: Client-Server Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytz

    # Start the server in the background
    - name: Start server
      run: |
        python pythonProject/tests/server_test.py &
      shell: bash

    # Run client tests
    - name: Run client tests
      run: |
        pytest pythonProject/tests/client_test.py -v
      shell: bash
